<option value="US" <?php echo selected( $default_country, 'US' ); ?>>United States</option>
<option value="GB" <?php echo selected( $default_country, 'GB' ); ?>>United Kingdom</option>
<option value="AF" <?php echo selected( $default_country, 'AF' ); ?>>Afghanistan</option>
<option value="AX" <?php echo selected( $default_country, 'AX' ); ?>>Aland Islands</option>
<option value="AL" <?php echo selected( $default_country, 'AL' ); ?>>Albania</option>
<option value="DZ" <?php echo selected( $default_country, 'DZ' ); ?>>Algeria</option>
<option value="AS" <?php echo selected( $default_country, 'AS' ); ?>>American Samoa</option>
<option value="AD" <?php echo selected( $default_country, 'AD' ); ?>>Andorra</option>
<option value="AO" <?php echo selected( $default_country, 'AO' ); ?>>Angola</option>
<option value="AI" <?php echo selected( $default_country, 'AI' ); ?>>Anguilla</option>
<option value="AQ" <?php echo selected( $default_country, 'AQ' ); ?>>Antarctica</option>
<option value="AG" <?php echo selected( $default_country, 'AG' ); ?>>Antigua and Barbuda</option>
<option value="AR" <?php echo selected( $default_country, 'AR' ); ?>>Argentina</option>
<option value="AM" <?php echo selected( $default_country, 'AM' ); ?>>Armenia</option>
<option value="AW" <?php echo selected( $default_country, 'AW' ); ?>>Aruba</option>
<option value="AU" <?php echo selected( $default_country, 'AU' ); ?>>Australia</option>
<option value="AT" <?php echo selected( $default_country, 'AT' ); ?>>Austria</option>
<option value="AZ" <?php echo selected( $default_country, 'AZ' ); ?>>Azerbaijan</option>
<option value="BS" <?php echo selected( $default_country, 'BS' ); ?>>Bahamas</option>
<option value="BH" <?php echo selected( $default_country, 'BH' ); ?>>Bahrain</option>
<option value="BD" <?php echo selected( $default_country, 'BD' ); ?>>Bangladesh</option>
<option value="BB" <?php echo selected( $default_country, 'BB' ); ?>>Barbados</option>
<option value="BY" <?php echo selected( $default_country, 'BY' ); ?>>Belarus</option>
<option value="BE" <?php echo selected( $default_country, 'BE' ); ?>>Belgium</option>
<option value="BZ" <?php echo selected( $default_country, 'BZ' ); ?>>Belize</option>
<option value="BJ" <?php echo selected( $default_country, 'BJ' ); ?>>Benin</option>
<option value="BM" <?php echo selected( $default_country, 'BM' ); ?>>Bermuda</option>
<option value="BT" <?php echo selected( $default_country, 'BT' ); ?>>Bhutan</option>
<option value="BO" <?php echo selected( $default_country, 'BO' ); ?>>Bolivia</option>
<option value="BA" <?php echo selected( $default_country, 'BA' ); ?>>Bosnia and Herzegovina</option>
<option value="BW" <?php echo selected( $default_country, 'BW' ); ?>>Botswana</option>
<option value="BV" <?php echo selected( $default_country, 'BV' ); ?>>Bouvet Island</option>
<option value="BR" <?php echo selected( $default_country, 'BR' ); ?>>Brazil</option>
<option value="IO" <?php echo selected( $default_country, 'IO' ); ?>>British Indian Ocean Territory</option>
<option value="BN" <?php echo selected( $default_country, 'BN' ); ?>>Brunei Darussalam</option>
<option value="BG" <?php echo selected( $default_country, 'BG' ); ?>>Bulgaria</option>
<option value="BF" <?php echo selected( $default_country, 'BF' ); ?>>Burkina Faso</option>
<option value="BI" <?php echo selected( $default_country, 'BI' ); ?>>Burundi</option>
<option value="KH" <?php echo selected( $default_country, 'KH' ); ?>>Cambodia</option>
<option value="CM" <?php echo selected( $default_country, 'CM' ); ?>>Cameroon</option>
<option value="CA" <?php echo selected( $default_country, 'CA' ); ?>>Canada</option>
<option value="CV" <?php echo selected( $default_country, 'CV' ); ?>>Cape Verde</option>
<option value="KY" <?php echo selected( $default_country, 'KY' ); ?>>Cayman Islands</option>
<option value="CF" <?php echo selected( $default_country, 'CF' ); ?>>Central African Republic</option>
<option value="TD" <?php echo selected( $default_country, 'TD' ); ?>>Chad</option>
<option value="CL" <?php echo selected( $default_country, 'CL' ); ?>>Chile</option>
<option value="CN" <?php echo selected( $default_country, 'CN' ); ?>>China</option>
<option value="CX" <?php echo selected( $default_country, 'CX' ); ?>>Christmas Island</option>
<option value="CC" <?php echo selected( $default_country, 'CC' ); ?>>Cocos (Keeling) Islands</option>
<option value="CO" <?php echo selected( $default_country, 'CO' ); ?>>Colombia</option>
<option value="KM" <?php echo selected( $default_country, 'KM' ); ?>>Comoros</option>
<option value="CG" <?php echo selected( $default_country, 'CG' ); ?>>Congo</option>
<option value="CD" <?php echo selected( $default_country, 'CD' ); ?>>Congo, The Democratic Republic of The</option>
<option value="CK" <?php echo selected( $default_country, 'CK' ); ?>>Cook Islands</option>
<option value="CR" <?php echo selected( $default_country, 'CR' ); ?>>Costa Rica</option>
<option value="CI" <?php echo selected( $default_country, 'CI' ); ?>>Cote D'ivoire</option>
<option value="HR" <?php echo selected( $default_country, 'HR' ); ?>>Croatia</option>
<option value="CU" <?php echo selected( $default_country, 'CU' ); ?>>Cuba</option>
<option value="CY" <?php echo selected( $default_country, 'CY' ); ?>>Cyprus</option>
<option value="CZ" <?php echo selected( $default_country, 'CZ' ); ?>>Czech Republic</option>
<option value="DK" <?php echo selected( $default_country, 'DK' ); ?>>Denmark</option>
<option value="DJ" <?php echo selected( $default_country, 'DJ' ); ?>>Djibouti</option>
<option value="DM" <?php echo selected( $default_country, 'DM' ); ?>>Dominica</option>
<option value="DO" <?php echo selected( $default_country, 'DO' ); ?>>Dominican Republic</option>
<option value="EC" <?php echo selected( $default_country, 'EC' ); ?>>Ecuador</option>
<option value="EG" <?php echo selected( $default_country, 'EG' ); ?>>Egypt</option>
<option value="SV" <?php echo selected( $default_country, 'SV' ); ?>>El Salvador</option>
<option value="GQ" <?php echo selected( $default_country, 'GQ' ); ?>>Equatorial Guinea</option>
<option value="ER" <?php echo selected( $default_country, 'ER' ); ?>>Eritrea</option>
<option value="EE" <?php echo selected( $default_country, 'EE' ); ?>>Estonia</option>
<option value="ET" <?php echo selected( $default_country, 'ET' ); ?>>Ethiopia</option>
<option value="FK" <?php echo selected( $default_country, 'FK' ); ?>>Falkland Islands (Malvinas)</option>
<option value="FO" <?php echo selected( $default_country, 'FO' ); ?>>Faroe Islands</option>
<option value="FJ" <?php echo selected( $default_country, 'FJ' ); ?>>Fiji</option>
<option value="FI" <?php echo selected( $default_country, 'FI' ); ?>>Finland</option>
<option value="FR" <?php echo selected( $default_country, 'FR' ); ?>>France</option>
<option value="GF" <?php echo selected( $default_country, 'GF' ); ?>>French Guiana</option>
<option value="PF" <?php echo selected( $default_country, 'PF' ); ?>>French Polynesia</option>
<option value="TF" <?php echo selected( $default_country, 'TF' ); ?>>French Southern Territories</option>
<option value="GA" <?php echo selected( $default_country, 'GA' ); ?>>Gabon</option>
<option value="GM" <?php echo selected( $default_country, 'GM' ); ?>>Gambia</option>
<option value="GE" <?php echo selected( $default_country, 'GE' ); ?>>Georgia</option>
<option value="DE" <?php echo selected( $default_country, 'DE' ); ?>>Germany</option>
<option value="GH" <?php echo selected( $default_country, 'GH' ); ?>>Ghana</option>
<option value="GI" <?php echo selected( $default_country, 'GI' ); ?>>Gibraltar</option>
<option value="GR" <?php echo selected( $default_country, 'GR' ); ?>>Greece</option>
<option value="GL" <?php echo selected( $default_country, 'GL' ); ?>>Greenland</option>
<option value="GD" <?php echo selected( $default_country, 'GD' ); ?>>Grenada</option>
<option value="GP" <?php echo selected( $default_country, 'GP' ); ?>>Guadeloupe</option>
<option value="GU" <?php echo selected( $default_country, 'GU' ); ?>>Guam</option>
<option value="GT" <?php echo selected( $default_country, 'GT' ); ?>>Guatemala</option>
<option value="GG" <?php echo selected( $default_country, 'GG' ); ?>>Guernsey</option>
<option value="GN" <?php echo selected( $default_country, 'GN' ); ?>>Guinea</option>
<option value="GW" <?php echo selected( $default_country, 'GW' ); ?>>Guinea-bissau</option>
<option value="GY" <?php echo selected( $default_country, 'GY' ); ?>>Guyana</option>
<option value="HT" <?php echo selected( $default_country, 'HT' ); ?>>Haiti</option>
<option value="HM" <?php echo selected( $default_country, 'HM' ); ?>>Heard Island and Mcdonald Islands</option>
<option value="VA" <?php echo selected( $default_country, 'VA' ); ?>>Holy See (Vatican City State)</option>
<option value="HN" <?php echo selected( $default_country, 'HN' ); ?>>Honduras</option>
<option value="HK" <?php echo selected( $default_country, 'HK' ); ?>>Hong Kong</option>
<option value="HU" <?php echo selected( $default_country, 'HU' ); ?>>Hungary</option>
<option value="IS" <?php echo selected( $default_country, 'IS' ); ?>>Iceland</option>
<option value="IN" <?php echo selected( $default_country, 'IN' ); ?>>India</option>
<option value="ID" <?php echo selected( $default_country, 'ID' ); ?>>Indonesia</option>
<option value="IR" <?php echo selected( $default_country, 'IR' ); ?>>Iran, Islamic Republic of</option>
<option value="IQ" <?php echo selected( $default_country, 'IQ' ); ?>>Iraq</option>
<option value="IE" <?php echo selected( $default_country, 'IE' ); ?>>Ireland</option>
<option value="IM" <?php echo selected( $default_country, 'IM' ); ?>>Isle of Man</option>
<option value="IL" <?php echo selected( $default_country, 'IL' ); ?>>Israel</option>
<option value="IT" <?php echo selected( $default_country, 'IT' ); ?>>Italy</option>
<option value="JM" <?php echo selected( $default_country, 'JM' ); ?>>Jamaica</option>
<option value="JP" <?php echo selected( $default_country, 'JP' ); ?>>Japan</option>
<option value="JE" <?php echo selected( $default_country, 'JE' ); ?>>Jersey</option>
<option value="JO" <?php echo selected( $default_country, 'JO' ); ?>>Jordan</option>
<option value="KZ" <?php echo selected( $default_country, 'KZ' ); ?>>Kazakhstan</option>
<option value="KE" <?php echo selected( $default_country, 'KE' ); ?>>Kenya</option>
<option value="KI" <?php echo selected( $default_country, 'KI' ); ?>>Kiribati</option>
<option value="KP" <?php echo selected( $default_country, 'KP' ); ?>>Korea, Democratic People's Republic of</option>
<option value="KR" <?php echo selected( $default_country, 'KR' ); ?>>Korea, Republic of</option>
<option value="KW" <?php echo selected( $default_country, 'KW' ); ?>>Kuwait</option>
<option value="KG" <?php echo selected( $default_country, 'KG' ); ?>>Kyrgyzstan</option>
<option value="LA" <?php echo selected( $default_country, 'LA' ); ?>>Lao People's Democratic Republic</option>
<option value="LV" <?php echo selected( $default_country, 'LV' ); ?>>Latvia</option>
<option value="LB" <?php echo selected( $default_country, 'LB' ); ?>>Lebanon</option>
<option value="LS" <?php echo selected( $default_country, 'LS' ); ?>>Lesotho</option>
<option value="LR" <?php echo selected( $default_country, 'LR' ); ?>>Liberia</option>
<option value="LY" <?php echo selected( $default_country, 'LY' ); ?>>Libyan Arab Jamahiriya</option>
<option value="LI" <?php echo selected( $default_country, 'LI' ); ?>>Liechtenstein</option>
<option value="LT" <?php echo selected( $default_country, 'LT' ); ?>>Lithuania</option>
<option value="LU" <?php echo selected( $default_country, 'LU' ); ?>>Luxembourg</option>
<option value="MO" <?php echo selected( $default_country, 'MO' ); ?>>Macao</option>
<option value="MK" <?php echo selected( $default_country, 'MK' ); ?>>Macedonia, The Former Yugoslav Republic of</option>
<option value="MG" <?php echo selected( $default_country, 'MG' ); ?>>Madagascar</option>
<option value="MW" <?php echo selected( $default_country, 'MW' ); ?>>Malawi</option>
<option value="MY" <?php echo selected( $default_country, 'MY' ); ?>>Malaysia</option>
<option value="MV" <?php echo selected( $default_country, 'MV' ); ?>>Maldives</option>
<option value="ML" <?php echo selected( $default_country, 'ML' ); ?>>Mali</option>
<option value="MT" <?php echo selected( $default_country, 'MT' ); ?>>Malta</option>
<option value="MH" <?php echo selected( $default_country, 'MH' ); ?>>Marshall Islands</option>
<option value="MQ" <?php echo selected( $default_country, 'MQ' ); ?>>Martinique</option>
<option value="MR" <?php echo selected( $default_country, 'MR' ); ?>>Mauritania</option>
<option value="MU" <?php echo selected( $default_country, 'MU' ); ?>>Mauritius</option>
<option value="YT" <?php echo selected( $default_country, 'YT' ); ?>>Mayotte</option>
<option value="MX" <?php echo selected( $default_country, 'MX' ); ?>>Mexico</option>
<option value="FM" <?php echo selected( $default_country, 'FM' ); ?>>Micronesia, Federated States of</option>
<option value="MD" <?php echo selected( $default_country, 'MD' ); ?>>Moldova, Republic of</option>
<option value="MC" <?php echo selected( $default_country, 'MC' ); ?>>Monaco</option>
<option value="MN" <?php echo selected( $default_country, 'MN' ); ?>>Mongolia</option>
<option value="ME" <?php echo selected( $default_country, 'ME' ); ?>>Montenegro</option>
<option value="MS" <?php echo selected( $default_country, 'MS' ); ?>>Montserrat</option>
<option value="MA" <?php echo selected( $default_country, 'MA' ); ?>>Morocco</option>
<option value="MZ" <?php echo selected( $default_country, 'MZ' ); ?>>Mozambique</option>
<option value="MM" <?php echo selected( $default_country, 'MM' ); ?>>Myanmar</option>
<option value="NA" <?php echo selected( $default_country, 'NA' ); ?>>Namibia</option>
<option value="NR" <?php echo selected( $default_country, 'NR' ); ?>>Nauru</option>
<option value="NP" <?php echo selected( $default_country, 'NP' ); ?>>Nepal</option>
<option value="NL" <?php echo selected( $default_country, 'NL' ); ?>>Netherlands</option>
<option value="AN" <?php echo selected( $default_country, 'AN' ); ?>>Netherlands Antilles</option>
<option value="NC" <?php echo selected( $default_country, 'NC' ); ?>>New Caledonia</option>
<option value="NZ" <?php echo selected( $default_country, 'NZ' ); ?>>New Zealand</option>
<option value="NI" <?php echo selected( $default_country, 'NI' ); ?>>Nicaragua</option>
<option value="NE" <?php echo selected( $default_country, 'NE' ); ?>>Niger</option>
<option value="NG" <?php echo selected( $default_country, 'NG' ); ?>>Nigeria</option>
<option value="NU" <?php echo selected( $default_country, 'NU' ); ?>>Niue</option>
<option value="NF" <?php echo selected( $default_country, 'NF' ); ?>>Norfolk Island</option>
<option value="MP" <?php echo selected( $default_country, 'MP' ); ?>>Northern Mariana Islands</option>
<option value="NO" <?php echo selected( $default_country, 'NO' ); ?>>Norway</option>
<option value="OM" <?php echo selected( $default_country, 'OM' ); ?>>Oman</option>
<option value="PK" <?php echo selected( $default_country, 'PK' ); ?>>Pakistan</option>
<option value="PW" <?php echo selected( $default_country, 'PW' ); ?>>Palau</option>
<option value="PS" <?php echo selected( $default_country, 'PS' ); ?>>Palestinian Territory, Occupied</option>
<option value="PA" <?php echo selected( $default_country, 'PA' ); ?>>Panama</option>
<option value="PG" <?php echo selected( $default_country, 'PA' ); ?>>Papua New Guinea</option>
<option value="PY" <?php echo selected( $default_country, 'PY' ); ?>>Paraguay</option>
<option value="PE" <?php echo selected( $default_country, 'PE' ); ?>>Peru</option>
<option value="PH" <?php echo selected( $default_country, 'PH' ); ?>>Philippines</option>
<option value="PN" <?php echo selected( $default_country, 'PN' ); ?>>Pitcairn</option>
<option value="PL" <?php echo selected( $default_country, 'PL' ); ?>>Poland</option>
<option value="PT" <?php echo selected( $default_country, 'PT' ); ?>>Portugal</option>
<option value="PR" <?php echo selected( $default_country, 'PR' ); ?>>Puerto Rico</option>
<option value="QA" <?php echo selected( $default_country, 'QA' ); ?>>Qatar</option>
<option value="RE" <?php echo selected( $default_country, 'RE' ); ?>>Reunion</option>
<option value="RO" <?php echo selected( $default_country, 'RO' ); ?>>Romania</option>
<option value="RU" <?php echo selected( $default_country, 'RU' ); ?>>Russian Federation</option>
<option value="RW" <?php echo selected( $default_country, 'RW' ); ?>>Rwanda</option>
<option value="SH" <?php echo selected( $default_country, 'SH' ); ?>>Saint Helena</option>
<option value="KN" <?php echo selected( $default_country, 'KN' ); ?>>Saint Kitts and Nevis</option>
<option value="LC" <?php echo selected( $default_country, 'LC' ); ?>>Saint Lucia</option>
<option value="PM" <?php echo selected( $default_country, 'PM' ); ?>>Saint Pierre and Miquelon</option>
<option value="VC" <?php echo selected( $default_country, 'VC' ); ?>>Saint Vincent and The Grenadines</option>
<option value="WS" <?php echo selected( $default_country, 'WS' ); ?>>Samoa</option>
<option value="SM" <?php echo selected( $default_country, 'SM' ); ?>>San Marino</option>
<option value="ST" <?php echo selected( $default_country, 'ST' ); ?>>Sao Tome and Principe</option>
<option value="SA" <?php echo selected( $default_country, 'SA' ); ?>>Saudi Arabia</option>
<option value="SN" <?php echo selected( $default_country, 'SN' ); ?>>Senegal</option>
<option value="RS" <?php echo selected( $default_country, 'RS' ); ?>>Serbia</option>
<option value="SC" <?php echo selected( $default_country, 'SC' ); ?>>Seychelles</option>
<option value="SL" <?php echo selected( $default_country, 'SL' ); ?>>Sierra Leone</option>
<option value="SG" <?php echo selected( $default_country, 'SG' ); ?>>Singapore</option>
<option value="SK" <?php echo selected( $default_country, 'SK' ); ?>>Slovakia</option>
<option value="SI" <?php echo selected( $default_country, 'SI' ); ?>>Slovenia</option>
<option value="SB" <?php echo selected( $default_country, 'SB' ); ?>>Solomon Islands</option>
<option value="SO" <?php echo selected( $default_country, 'SO' ); ?>>Somalia</option>
<option value="ZA" <?php echo selected( $default_country, 'ZA' ); ?>>South Africa</option>
<option value="GS" <?php echo selected( $default_country, 'GS' ); ?>>South Georgia and The South Sandwich Islands</option>
<option value="ES" <?php echo selected( $default_country, 'ES' ); ?>>Spain</option>
<option value="LK" <?php echo selected( $default_country, 'LK' ); ?>>Sri Lanka</option>
<option value="SD" <?php echo selected( $default_country, 'SD' ); ?>>Sudan</option>
<option value="SR" <?php echo selected( $default_country, 'SR' ); ?>>Suriname</option>
<option value="SJ" <?php echo selected( $default_country, 'SJ' ); ?>>Svalbard and Jan Mayen</option>
<option value="SZ" <?php echo selected( $default_country, 'SZ' ); ?>>Swaziland</option>
<option value="SE" <?php echo selected( $default_country, 'SE' ); ?>>Sweden</option>
<option value="CH" <?php echo selected( $default_country, 'CH' ); ?>>Switzerland</option>
<option value="SY" <?php echo selected( $default_country, 'SY' ); ?>>Syrian Arab Republic</option>
<option value="TW" <?php echo selected( $default_country, 'TW' ); ?>>Taiwan, Province of China</option>
<option value="TJ" <?php echo selected( $default_country, 'TJ' ); ?>>Tajikistan</option>
<option value="TZ" <?php echo selected( $default_country, 'TZ' ); ?>>Tanzania, United Republic of</option>
<option value="TH" <?php echo selected( $default_country, 'TH' ); ?>>Thailand</option>
<option value="TL" <?php echo selected( $default_country, 'TL' ); ?>>Timor-leste</option>
<option value="TG" <?php echo selected( $default_country, 'TG' ); ?>>Togo</option>
<option value="TK" <?php echo selected( $default_country, 'TK' ); ?>>Tokelau</option>
<option value="TO" <?php echo selected( $default_country, 'TO' ); ?>>Tonga</option>
<option value="TT" <?php echo selected( $default_country, 'TT' ); ?>>Trinidad and Tobago</option>
<option value="TN" <?php echo selected( $default_country, 'TN' ); ?>>Tunisia</option>
<option value="TR" <?php echo selected( $default_country, 'TR' ); ?>>Turkey</option>
<option value="TM" <?php echo selected( $default_country, 'TM' ); ?>>Turkmenistan</option>
<option value="TC" <?php echo selected( $default_country, 'TC' ); ?>>Turks and Caicos Islands</option>
<option value="TV" <?php echo selected( $default_country, 'TV' ); ?>>Tuvalu</option>
<option value="UG" <?php echo selected( $default_country, 'UG' ); ?>>Uganda</option>
<option value="UA" <?php echo selected( $default_country, 'UA' ); ?>>Ukraine</option>
<option value="AE" <?php echo selected( $default_country, 'AE' ); ?>>United Arab Emirates</option>
<option value="UM" <?php echo selected( $default_country, 'UM' ); ?>>United States Minor Outlying Islands</option>
<option value="UY" <?php echo selected( $default_country, 'UY' ); ?>>Uruguay</option>
<option value="UZ" <?php echo selected( $default_country, 'UZ' ); ?>>Uzbekistan</option>
<option value="VU" <?php echo selected( $default_country, 'VU' ); ?>>Vanuatu</option>
<option value="VE" <?php echo selected( $default_country, 'VE' ); ?>>Venezuela</option>
<option value="VN" <?php echo selected( $default_country, 'VN' ); ?>>Viet Nam</option>
<option value="VG" <?php echo selected( $default_country, 'VG' ); ?>>Virgin Islands, British</option>
<option value="VI" <?php echo selected( $default_country, 'VI' ); ?>>Virgin Islands, U.S.</option>
<option value="WF" <?php echo selected( $default_country, 'WF' ); ?>>Wallis and Futuna</option>
<option value="EH" <?php echo selected( $default_country, 'EH' ); ?>>Western Sahara</option>
<option value="YE" <?php echo selected( $default_country, 'YE' ); ?>>Yemen</option>
<option value="ZM" <?php echo selected( $default_country, 'ZM' ); ?>>Zambia</option>
<option value="ZW" <?php echo selected( $default_country, 'ZW' ); ?>>Zimbabwe</option>