<?php
	class YIKES_Inc_Easy_MailChimp_Public_Ajax
	{
	
		/**
		 * Thetext domain of this plugin
		 *
		 * @since    1.0.0
		 * @access   private
		 * @var      string    $version    Used for internationalization
		 */		 
		public function __construct() {				
			// ajax process form submission
			add_action( 'wp_ajax_nopriv_process_form_submission', array( $this , 'process_form_submission' ), 10 );
			add_action( 'wp_ajax_process_form_submission', array( $this , 'process_form_submission' ), 10 );
			
			// ajax send update emails
			add_action( 'wp_ajax_easy_forms_send_email', array( $this , 'sendUpdateProfileEmail' ), 10 );
			add_action( 'wp_ajax_easy_forms_send_email', array( $this , 'sendUpdateProfileEmail' ), 10 );
			
			// increase submission count for a given form on successful submit
			add_action( 'wp_ajax_nopriv_increase_submission_count' , array( $this , 'increase_submission_count' ), 10 );	
			add_action( 'wp_ajax_increase_submission_count' , array( $this , 'increase_submission_count' ), 10 );	
		}
		
		/*
		*	Process form submisssions sent via ajax from the front end
		*	$form_data - serialized form data submitted
		*/
		public function process_form_submission() {
			// include our ajax processing file
			include_once( YIKES_MC_PATH . 'public/partials/shortcodes/process/process_form_submission_ajax.php' );
			exit();
			wp_die();
		}
		
		/*
		*	Increase the submission count for a given 
		*	$form_id - id of the form to increase submission count by 1
		*/
		public function increase_submission_count() {
			// store our posted form ID
			$form_id = $_POST['form_id'];
			global $wpdb;
			// query the form
			$form_results = $wpdb->get_results( 'SELECT * FROM ' . $wpdb->prefix . 'yikes_easy_mc_forms WHERE id = ' . $form_id . '', ARRAY_A );
			$form_data = $form_results[0];
			// increase the submission
			$form_data['submissions']++;
			// update the value in the database
			$wpdb->update( 
				$wpdb->prefix . 'yikes_easy_mc_forms',
					array( 
						'submissions' => $form_data['submissions'],
					),
					array( 'ID' => $form_id ), 
					array(
						'%d',
					), 
					array( '%d' ) 
				);	
			exit();
			wp_die();
		}
		
		/*
			Send Update Profile Email
			@since v6.0.4.1
		*/
		public function sendUpdateProfileEmail() {
			$user_email = $_POST['user_email'];
			$list_id = $_POST['list_id'];
			$api = new Mailchimp( get_option( 'yikes-mc-api-key' , '' ) );
			$explode_key = explode( '-' , get_option( 'yikes-mc-api-key' , '' ) );
			$data_center = $explode_key[1];
			$full_site_url = get_bloginfo('url');
			try {
				// get the site URL
				// not sure this needs its own API call
				$account_details = $api->call( 'helper/account-details', array('apikey' => get_option( 'yikes-mc-api-key' , '' ) ) );
				// get the list details (default from name, default from email)
				$list_details = $api->call( 'lists/list', 
					array(
						'apikey' => get_option( 'yikes-mc-api-key' , '' ),
						'filters' => array(
							'list_id' => $list_id
						)
					) 
				);
				// get the subscribers info
				$subscriber_account_details = $api->call('lists/member-info', 
					array(
						'id'	=>	$list_id,
						'emails'	=>	array(
							0 => array(
										'email' => $user_email,
									),
						)	
					)	
				);
				$subscriber_id = $subscriber_account_details['data'][0]['id'];
				$explode_url = explode( '.' , $account_details['contact']['url'] );
				$subject = 'MailChimp Profile Update';
				$headers = 'From: ' . $list_details['data'][0]['default_from_name'] . ' <' . $list_details['data'][0]['default_from_email'] . '>' . "\r\n";
				$headers .= 'Content-type: text/html';
					$email_content = '<p>Dear user,</p> <p>A request has been made to update your account information. To do so use the following link: <a href="http://' . $explode_url[1] . '.' . $data_center . '.list-manage1.com/profile?u=' . $account_details['user_id'] . '&id=' . $list_id .'&e=' . $subscriber_id . '" title="Update MailChimp Profile">Update Profile Info.</a>';
					$email_content .= "<p>If you didn't request this update, please disregard this email.</p>";
					$email_content .= '<p>&nbsp;</p>';
					$email_content .= '<p>This email was sent from : ' . $full_site_url . '</p>'; 
					$email_content .= '<p>&nbsp;</p>'; 
					$email_content .= '<p>&nbsp;</p>';
					$email_content .= '<p style="font-size:13px;margin-top:5em;float:right;"><em>this email was generated by the <a href="http://www.wordpress.org/plugins/yikes-inc-easy-mailchimp-extender/" target="_blank">Easy Forms for MailChimp by YIKES</a> plugin, created by <a href="http://www.yikesinc.com" target="_blank">YIKES Inc.</a></em></p>';
				/* Confirm that the email was sent */
				if ( wp_mail( $user_email, $subject, $email_content, $headers ) ) {
					wp_send_json_success(
						array(
							'response_text' => '<span class="yikes-easy-mc-success-message">' . sprintf( __( '%s Update email successfully sent. Please check your inbox for the message.' , 'yikes-inc-easy-mailchimp-extender' ), '&#10004;' ) . '</span>',
						)
					);
					exit;
				} else {
					wp_send_json_error(
						array(
							'response_text' => '<span class="yikes-easy-mc-error-message">' . sprintf( __( '%s Email failed to send. Please contact the site administrator.' , 'yikes-inc-easy-mailchimp-extender' ), '&#10005;' ) . '</span>',
						)
					);
					exit;
				} 
				// print_r($account_details);	
			} catch( Exception $e ) {
				$errorMessage = '<span class="error">' . __( 'Error sending update profile email. Please contact the site administrator.' , 'yikes-inc-easy-mailchimp-extender' ) . '</span>';
				echo $errorMessage;
			}
		} // end sendUpdateProfileEmail();
							
	} // end class
	
	new YIKES_Inc_Easy_MailChimp_Public_Ajax();
	
?>